import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"



const inter = Inter({ subsets: ['latin'] })

function Home(){
  const { data: session } = useSession()
  
  if(session){
  return (
    <>
      <Head>
        <title>Gjeste Bok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    
      </main>
    </>
  )
  }
  return (
    <>
      <Head>
        <title>Logg inn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.mainNotLoggedIn}>
        <h1>Logg inn for å se inlegg</h1>
        </main>
    </>
  )
}

// app.listen(port, () => {
//   console.log(`Example app listening on port ${port}`)
// })

export default Home
